"use client";

import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { useExportAnalytics } from "@/lib/api/queries";
import { AsyncContent } from "@/components/shared/async-content";
import { ChartTooltip } from "@/components/dashboard/chart-tooltip";

export function ExportAnalyticsChart() {
  const { data, isPending, isError, error } = useExportAnalytics();
  const exportAnalytics = data ?? [];
  return (
    <Card className="glass overflow-hidden">
      <CardHeader>
        <CardTitle>Export Analytics</CardTitle>
        <p className="mt-1 text-xs text-muted-foreground">Exports generated by format, per month</p>
      </CardHeader>
      <AsyncContent
        isPending={isPending}
        isError={isError}
        error={error}
        isEmpty={exportAnalytics.length === 0}
        emptyMessage="No exports yet."
        className="h-72"
      >
      <div className="h-72 w-full px-2 pb-4 pt-4 sm:px-4">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={exportAnalytics} margin={{ top: 4, right: 8, left: -16, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
            <XAxis
              dataKey="month"
              stroke="var(--color-border)"
              tick={{ fill: "var(--color-muted-foreground)", fontSize: 12 }}
              tickLine={false}
              axisLine={false}
            />
            <YAxis
              stroke="var(--color-border)"
              tick={{ fill: "var(--color-muted-foreground)", fontSize: 12 }}
              tickLine={false}
              axisLine={false}
              width={32}
            />
            <Tooltip content={<ChartTooltip />} cursor={{ fill: "var(--color-surface-2)" }} />
            <Legend
              wrapperStyle={{ fontSize: 12, color: "var(--color-muted-foreground)" }}
              iconType="circle"
              iconSize={8}
            />
            <Bar dataKey="csv" name="CSV" stackId="exports" fill="var(--color-primary)" radius={[0, 0, 0, 0]} maxBarSize={28} />
            <Bar dataKey="excel" name="Excel" stackId="exports" fill="var(--color-accent)" maxBarSize={28} />
            <Bar dataKey="pdf" name="PDF" stackId="exports" fill="var(--color-success)" radius={[6, 6, 0, 0]} maxBarSize={28} />
          </BarChart>
        </ResponsiveContainer>
      </div>
      </AsyncContent>
    </Card>
  );
}
