"""add api_providers.credit_cost for provider-specific credit metering

Revision ID: 061f53392c57
Revises: 6db480726061
Create Date: 2026-07-30 07:30:03.695308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061f53392c57'
down_revision: Union[str, None] = '6db480726061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_providers', sa.Column('credit_cost', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_providers', 'credit_cost')
    # ### end Alembic commands ###
